### ISSUE TITLE
arm_nwk_interface_init  compiler diagnostic

### ISSUE THREAD

**Issue by kmdewaal** [ARMmbed/sal-stack-nanostack#10]
I get a compiler diagnostic about the use of a literal string as the interface name, as shown here:

> C:/_ddm/openais-eu-project/openais-mbed-common/source/network.cpp:186:92: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
>              eth_if_id = arm_nwk_interface_init(NET_INTERFACE_ETHERNET, net_eth_id, "EthNet");
> 

Reason is that the third parameter of function arm_nwk_interface_init, defined in file net_interface.h, uses type "char *" for the interface name:

> extern int8_t arm_nwk_interface_init(net_interface_type_e type, uint8_t phy_driver_id, char *interface_name_ptr);

I suggest to change the type of the interface_name_ptr from "char *" to "const char *", unless it is the intention that the interface name is actually modified by arm_nwk_interface_init.
Of course, the implementation of the arm_nwk_interface_init needs to be modified as well.
Note that I could not find the source code of this function.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2412

**Comment by SeppoTakalo** [comment]
Fixed in vesion 4.0.x
