### ISSUE TITLE
Request: IPv6 multicast, MPL also supports Ethernet connections.

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/sal-stack-nanostack#15]
Feature request:

To improve the multicast reliability also for cabled Ethernet connections, it would be great MPL supports Ethernet too. 

Thanks in advance

**Comment by kjbracey-arm** [comment]
Interesting idea. Not sure it's merited on reliability grounds - Ethernet already achieves "expected" reliability for the IP layer, maybe better. I don't see that MPL is going to help much. Take it from 99.9% to 99.99%?

IP isn't a reliable protocol in either multicast or unicast form - higher layers need to be robust to a small amount of packet loss.

But there may be some merit in MPL as part of a multicast routing mechanism between Ethernet and mesh. At present Nanostack does some forwarding of site-local multicast between the two, but it's ad-hoc, and could conceivably cause loops. Using MPL across the border router would be more solid. This is already under consideration.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2732

**Comment by TuomoHautamaki** [comment]
Thank you for the idea/request! 
It's been now evaluated but we don't see a real benefit to develop this one. Therefore closing the ticket
