### ISSUE TITLE
Implement Thread network in Native Ubuntu PC and test functionality

### ISSUE THREAD

**Issue by Praveen-Kumar-K** [ARMmbed/sal-stack-nanostack#17]
Hi All,
I am interested to test the Thread network applications initially on my Native Ubuntu 12.04 PC. Can any one give me the document or Guide me How to implement Thread network on my PC. Please any one help me in this regard.

Thanks,
Praveen Kumar K

**Comment by mikter** [comment]
If you require border router for PC to get access to Thread network you need to create Border router application with supported hardware and connect it to PC with SLIP or ethernet.

Example of border router implementation can be found from here:
https://github.com/ARMmbed/thread-testapp-private

Supported platforms and hardware can be found from example applications. There is also border router binary for 6LoWPAN Gateway hardware.
see https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-client/

**Comment by SeppoTakalo** [comment]
I'm closing this, as we only support our 6LoWPAN/Thread stack as part of mbed OS.
