### ISSUE TITLE
regarding Thread Stack

### ISSUE THREAD

**Issue by Praveen-Kumar-K** [ARMmbed/sal-stack-nanostack#19]
Hi,
I have seen that sal-stack-nanostack, will support Thread network also. May i know, weather it will support entire Thread stack, is there any registration required to access the Thread Stack, what are the hardware platforms support for this Thread and is it a openthread or Thread.
It would be very glad if any one give me the information.

Thanks,
Praveen Kumar k

**Comment by maansaari** [comment]
Hello Praveen Kumar,

The sal-stack-nanostack has Thread stack implementation by ARM. It's ARM internal development, not the openthread. It's available for mbed developers via https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-client/.

Best Regards, 
Kirsi Maansaari
