### ISSUE TITLE
Missing mac_filter_api definitions

### ISSUE THREAD

**Issue by tibmanus** [ARMmbed/sal-stack-nanostack#23]
I would like to test my application and "force" my nodes into a multihop setup. I thought the MAC filtering APIs described in `mac_filter_api.h` would be great for this, however when I try to use them I get `undefined reference` to the functions. I guess their respective object file was not included in this repo. Any chance to fix this?

**Comment by kjbracey-arm** [comment]
Which function in particular is giving an error?  All of them? I don't see any reason the filter functionality should be missing.

Ah, I note the header does not have `extern "C"` protection - are you including it from C++?

**Comment by tibmanus** [comment]
Oh! Should have thought so! I didn't think about `extern "C"`. 
Thanks for the help, it works now!
