### ISSUE TITLE
Thread discovery responses are broken

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/sal-stack-nanostack#25]
When Nanostack responds to an MLE discovery request, it replies using link security instead of in the clear. Obviously, this message should be passed in the clear, because how else will a Thread node without precommissioned keys ever get to know about the network?

**Comment by mikter** [comment]
MLE discovery response uses the same preconfigured key that is used in sending of the MLE Discovery Request. Thread specification defines this key in MAC key mode 2. That is the reason all nodes know the key before they have any secret material from the network. Allowing all devices to be able to decrypt this message.

The mistake here is that key id mode 2 should be only used when sending messages to multicast PANID. and as such MLE Discovery Response should be sent as clear.

**Comment by mikter** [comment]
This issue is fixed in sal-stack-nanostack-private and if you are mbed partner you can use the latest version from there.

Link to commit:
https://github.com/ARMmbed/sal-stack-nanostack-private/commit/db097a636b6a2c31f8608b0bd52c4bffe36a322d

**Comment by artokin** [comment]
Closed as requested by Mika
