### ISSUE TITLE
Does nanostack support non-beacon-enable mode?

### ISSUE THREAD

**Issue by liujian0927** [ARMmbed/sal-stack-nanostack#26]
In mbed docs, it describes 6LoWPAN nodes use beacons to find the specific network that the device wants to join.  Do the 6LoWPAN nodes must be operate on  beacon-enable mode?  
CA8210 which is IEEE802.15.4 RF dose not support beacon-enable mode ,so this RF couldn't work on nanostack?
Dose nanostack support non-beacon-enable mode?if it supports non-beacon-enable mode and how to set nanostack operate on  beacon-enable mode?

Thanks,
Jliu

@AnttiKauppila 
cc @cyliangtw   ,@HarryMorris

**Comment by mikaleppanen** [comment]
6LoWPAN works in nonbeacon-enabled personal area network mode as in IEEE802.15.4 meaning that it does not broadcast periodical beacons. Beacons are used only in network discovery.

Best Regards,
Mika

**Comment by liujian0927** [comment]
Hi, @mikaleppanen  @AnttiKauppila 
I used the vendor MAC instead of sw-MAC.when I've  received a beacon during the scan . However it seems like the nanostack isn't happy with it for some reason... I added some printf messages to make sure the scan confirm looked okay:
![capture](https://cloud.githubusercontent.com/assets/23413097/22144035/3dbb96e4-df37-11e6-8411-2de9ba05985e.JPG)
All these parameters are fine so I'm not sure why I'm getting this "No Beacons" message. I can't see which file this code is in either so I'm not sure where the "Mac scan confirm:No Beacons" message comes from.

**Comment by AnttiKauppila** [comment]
Can you verify you have called mlme_indication() with primitive MLME_BEACON_NOTIFY after receiving a beacon. That is needed for Nanostack to receive beacon payloads.
Other thing to check would be mac_api_t pointer's "parent_id" variable. That must be the same as what is received in mac_api_initialize.
