### ISSUE TITLE
Example wired nano IPv6

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/sal-stack-nanostack#28]
Hello,

Is there a code example of the initialization part available to use the wired nanostack in IPv6 mode on a K64. We had the wired nanostack running with mbed 5.1 and a modified NanostackInterface.cpp. I have understood mbed 5.4 has an ethernet version available that requires no modification. Thanks in advance for your help.

**Comment by SeppoTakalo** [comment]
Hi EduarPon,

I don't think we have public examples of that.

Basically you need this driver in your application: https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth

Then include Nanostack in the build by having following in the `mbed_app.json`
```
{
    "target_overrides": {
        "*": {
            "target.features_add": ["NANOSTACK", "LOWPAN_BORDER_ROUTER", "COMMON_PAL"],
        }
    }
}
```

Then initialize it as follows:
```
#include "NanostackInterface.h"
#include "NanostackEthernetPhyK64F.h"

NanostackEthernetPhyK64F phy;
NanostackEthernetInterface eth0;

int main(void) {
    eth0.initialize(&phy);
}
```

Now you can utilize the `eth0` as a interface for opening sockets.
```
    UDPSocket socket;
    socket.open(&eth0);
```

**Comment by EduardPon** [comment]
Thanks, for your help.
