### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/sal-stack-nanostack#3]
The license declared in module.json doesn't match the license file. sal-stack-lwip includes an example of [referencing a custom license file](https://github.com/ARMmbed/sal-stack-lwip/blob/master/module.json#L29).

@SeppoTakalo

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/ONME-1696

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: ONME-1994

**Comment by SeppoTakalo** [comment]
Fixed in v3.0.3
