### ISSUE TITLE
nanostack support for nRF52840/nRF52832?

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/sal-stack-nanostack#31]
Any word on nanostack drivers for some of the Cortex-M SOC's with built in radios?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3125

**Comment by TuomoHautamaki** [comment]
Unfortunately we do not have visibility to upcoming driver updates. RF drivers live outside of the nanostack and are not provided by us (excluding few examples). Therefore we are not able to provide you the information you requested.
