### ISSUE TITLE
Thread Test harness failure with ARM as DUT

### ISSUE THREAD

**Issue by ganguricharishma** [ARMmbed/sal-stack-nanostack#32]
Hi,
I had connected 3 ARM devices with 1 ARM as DUT(Leader Role).
**Harness version** - Thread Test Harness V1.1 Beta v1.0
**Reference devices and their firmware**:  ARM :( NXP FRDM-K64F with Firefly 6LoWPAN shield) and **Firmware** : mbed-client-cliapp_16_11_04.bin

Observed some Failure cases. Can anyone figure out the issue of failure? Harness reports are attached for reference.
[Leader__2017_07_27-18_15_01.pdf](https://github.com/ARMmbed/sal-stack-nanostack/files/1192743/Leader__2017_07_27-18_15_01.pdf)
[pcaps.zip](https://github.com/ARMmbed/sal-stack-nanostack/files/1192745/pcaps.zip)

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3155

**Comment by deepakvenugopal** [comment]
@ganguricharishma thanks for reporting this issue. Could you please report Thread harness related issues to the Thread Group JIRA pages?

**Comment by TuomoHautamaki** [comment]
Set to closed as Thread Harness issues need to be reported to the Thread Group JIRA
