### ISSUE TITLE
Issue with sal-stack-nanostack objects built by ARM

### ISSUE THREAD

**Issue by bangaragirinxp** [ARMmbed/sal-stack-nanostack#6]
We built mbed-thread-minimal example for JN5179 device using Codered LPCXpresso tool chain & found that the example is not working correctly. We have the following observations:
     •	With sal-stack-nanostack objects built by ARM – We can observe 3 packets sent over the air (observed in Ubisys sniffer) & then no packets are sent
     •	With sal-stack-nanostack objects built by NXP using LPCXpresso tool chain – We can observe packets sent over the air in periodic interval (observed in Ubisys sniffer)

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2379

**Comment by mlnx** [comment]
@bangaragirinxp thanks for raising this issue.
Could you please describe the steps you are following to generate the objects with your toolchain?

**Comment by mlnx** [comment]
@SeppoTakalo could you please have a look into this?

**Comment by bangaragirinxp** [comment]
We built the mbed-thread-minimal application using stack source code & then copied the object files into sal-stack-nanostack.

**Comment by SeppoTakalo** [comment]
I believe this is related: ARMmbed/mbed-client-example-6lowpan#35

**Comment by SeppoTakalo** [comment]
I'm not familiar with the Codered LPCXpresso toolchain. What compiler does it use? (ARMCC or GCC, or other)

**Comment by bangaragirinxp** [comment]
LPCXpresso is based on GCC. You can download it from here - https://www.lpcware.com/lpcxpresso/downloads/windows

**Comment by mlnx** [comment]
@SeppoTakalo I guess the object files in this repo are not updated and do not match the latest changes introduced in the sources?

**Comment by bangaragirinxp** [comment]
We are using sal-stack-nanostack version 3.0.5. We built the objects from sources from same version.

**Comment by SeppoTakalo** [comment]
This issue might relate to object files been build using different GCC version, and probably using different build flags.
If you can continue on using the source files from the same version tag (using `yotta link`) and it resolves your problem, then please do so.
We need to continue on investigating this, but I'm not expecting any near time changes because we need to most probably agree on what GCC versions we actually support with these binary modules.

**Comment by mlnx** [comment]
@SeppoTakalo
Please ignore the Code-red toolchain for now. I’m able to reproduce this with the default [ARM Launchpad](https://launchpad.net/gcc-arm-embedded) toochain (4.9.3).

Please find attached scripts to reproduce the builds:
- [setup_nanostack_source.txt](https://github.com/ARMmbed/sal-stack-nanostack/files/108212/setup_nanostack_source.txt)
- [setup_nanostack_obj.txt](https://github.com/ARMmbed/sal-stack-nanostack/files/108213/setup_nanostack_obj.txt)

There is clearly a mismatch on the behaviour between the nanostack source code and the object version.

This is affecting to people who do not have access to the nanostack source code, so your help to fix this will be very much appreciated!

**Comment by mlnx** [comment]
@bangaragirinxp I'm afraid I'm no longer able to reproduce the problem.
The object file version seems to be working fine now.
I'd suggest to give it a try again, and even test https://github.com/ARMmbed/sal-stack-nanostack/commit/0ffeda15a296fc5aa06292f00725fee9c11ec233

**Comment by SeppoTakalo** [comment]
Verified in https://github.com/ARMmbed/mbed-thread-jn517x-example/issues/1#issuecomment-184299195 that this issue has no relation to binary object build by us.
