### ISSUE TITLE
Device disconnected during long duration testing

### ISSUE THREAD

**Issue by bangaragirinxp** [ARMmbed/sal-stack-nanostack#7]
We are executing the long duration tests using mbed-thread-minimal example (for few days) on our JN5179 device. Our test setup has the following devices:
  - mbed border router connected to test PC (mbed ATMEL gateway board)
  - one K64F node
  - two JN5179 nodes
We observe the packets both in  Wireshark on test PC & over the air packets in Ubisys sniffer.
When we start the tests, all three devices are connected & are visible in mDS on test PC.
We can also observe periodic packets sent by the devices.
After 36 hours of operation, we observe that nodes are getting disconnected & no over the air packets are observed. First JN5179 nodes are disconnected, later K64F node is also disconnected. We also capture the error logs on serial prompt for the devices. Please find the serial output log from K64F node
[Freescalenode.txt](https://github.com/ARMmbed/sal-stack-nanostack/files/106479/Freescalenode.txt)

**Comment by mlnx** [comment]
cc @mikter
Could you please have a look into this and help to reproduce internally?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2380

**Comment by SeppoTakalo** [comment]
Hi @bangaragirinxp Do you still have the serial logs of the nodes? We are interested to see the full logs.

**Comment by bangaragirinxp** [comment]
This is the full log we got. Please note that we enabled only the error messages.

**Comment by mlnx** [comment]
The system is now much more stable and doesn't crash for at least 7 days.
If you see problems, please re-open and provide detailed log info.

**Comment by markus-becker-tridonic-com** [comment]
@mlnx which commit has the fix?

**Comment by mlnx** [comment]
This is the PR that fixes the problem:
https://github.com/ARMmbed/target-kinetis-k64-gcc/issues/4
https://github.com/ARMmbed/target-kinetis-k64-gcc/pull/5
