### ISSUE TITLE
mbed-client-c does not meet specification ^1.0.0 required by sal-stack-nanostack

### ISSUE THREAD

**Issue by devran01** [ARMmbed/sal-stack-nanostack#9]
Building an application using mbed-client and sal-stack-nanostack triggers "error: mbed-client-c does not meet specification ^1.0.0 required by sal-stack-nanostack" as the latest version of mbed-client-c is 2.2.5.

**Comment by yogpan01** [comment]
@devran01 There is a fix coming for this  https://github.com/ARMmbed/sal-stack-nanostack-private/pull/267

**Comment by devran01** [comment]
@yogpan01 Thank you for the update.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2405

**Comment by SeppoTakalo** [comment]
Fixed in v3.0.6.
